

services:
  tinyarrows:
    build:
      context: .
      dockerfile: Dockerfile
    image: tinyarrows:latest
    ports:
      - 5001:5001
    volumes:
      - ../MyArrows/archive:/TinyArrows/archive
      - ../MyArrows/Work:/TinyArrows/Work
      - ../MyArrows/Projects:/TinyArrows/Projects
    depends_on:
      - mariadb
      - mongodb

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 05291999
      MYSQL_DATABASE: TNT_Project
      MYSQL_USER: arrows
      MYSQL_PASSWORD: reaction
    command: --bind-address=0.0.0.0
    restart: always
    volumes:
      - ../MyArrows/mariadb:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ../MyArrows/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: arrows
      MONGO_INITDB_ROOT_PASSWORD: reaction
      MONGO_INITDB_DATABASE: Arrows # Set the default database name for MongoDB
    command: mongod --auth --bind_ip_all # Enable authentication and bind to all interfaces

