# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install system dependencies needed for MariaDB, MongoDB, and Open Babel
RUN apt-get update && apt-get install -y mariadb-client mongodb-clients openbabel

# Copy the eric3.sql file into the container
COPY backup/eric3.sql /docker-entrypoint-initdb.d/eric3.sql

# Install the required Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port your Flask app is running on
EXPOSE 5000

# Define the command to run your app using gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]

